import * as esbuild from "esbuild";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { argv } from "node:process";

const watch = argv.includes("--watch");
const outFile = "../assets/editor.js";
const hostCopies = [
  "../apps/desktop/assets/editor.js",
  "../apps/mobile/assets/editor.js",
];

async function syncHostCopies() {
  await Promise.all(
    hostCopies.map(async (target) => {
      await mkdir(dirname(target), { recursive: true });
      await copyFile(outFile, target);
    })
  );
}

async function stripTrailingWhitespace(file) {
  const content = await readFile(file, "utf8");
  const normalized = content.replace(/[ \t]+$/gm, "");
  if (normalized !== content) {
    await writeFile(file, normalized);
  }
}

const ctx = await esbuild.context({
  entryPoints: ["src/editor-tiptap-entry.js"],
  bundle: true,
  format: "iife",
  outfile: outFile,
  minify: !watch,
  sourcemap: watch ? "inline" : false,
  loader: {
    ".jsx": "jsx",
  },
  banner: {
    js: "// Papyro editor bundle - generated by esbuild. Do not edit directly.",
  },
  plugins: [
    {
      name: "sync-host-assets",
      setup(build) {
        build.onEnd(async (result) => {
          if (result.errors.length > 0) return;

          await stripTrailingWhitespace(outFile);
          await syncHostCopies();
          console.log(
            `Synced editor bundle to ${hostCopies
              .map((target) => target.replace("../", ""))
              .join(", ")}`
          );
        });
      },
    },
  ],
});

if (watch) {
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await ctx.rebuild();
  await ctx.dispose();
  console.log("Build complete: assets/editor.js");
}
