import * as esbuild from "esbuild";
import * as sass from "sass";
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { argv } from "node:process";

const watch = argv.includes("--watch");
const outFile = "../assets/editor.js";
const cssOutFile = "../assets/editor.css";
const hostCopies = [
  "../apps/desktop/assets/editor.js",
  "../apps/mobile/assets/editor.js",
];

async function syncHostCopies() {
  await Promise.all(
    hostCopies.map(async (target) => {
      await mkdir(dirname(target), { recursive: true });
      await copyFile(outFile, target);
    })
  );
}

async function stripTrailingWhitespace(file) {
  const content = await readFile(file, "utf8");
  const normalized = content.replace(/[ \t]+$/gm, "");
  if (normalized !== content) {
    await writeFile(file, normalized);
  }
}

const ctx = await esbuild.context({
  entryPoints: ["src/editor-tiptap-entry.js"],
  bundle: true,
  format: "iife",
  outfile: outFile,
  minify: !watch,
  sourcemap: watch ? "inline" : false,
  loader: {
    ".jsx": "jsx",
    ".scss": "css",
  },
  alias: {
    "@": join(process.cwd(), "src"),
  },
  banner: {
    js: "// Papyro editor bundle - generated by esbuild. Do not edit directly.",
  },
  plugins: [
    {
      name: "scss",
      setup(build) {
        build.onLoad({ filter: /\.scss$/ }, async (args) => {
          const result = sass.compile(args.path, {
            loadPaths: [process.cwd()],
            style: "compressed",
          });
          const styleId = `papyro-editor-style-${Buffer.from(args.path)
            .toString("base64url")
            .slice(0, 24)}`;
          return {
            contents: `
const css = ${JSON.stringify(result.css)};
if (typeof document !== "undefined" && css) {
  const id = ${JSON.stringify(styleId)};
  if (!document.querySelector(\`style[data-papyro-editor-style="\${id}"]\`)) {
    const style = document.createElement("style");
    style.dataset.papyroEditorStyle = id;
    style.textContent = css;
    document.head.appendChild(style);
  }
}
export default css;
`,
            loader: "js",
          };
        });
      },
    },
    {
      name: "sync-host-assets",
      setup(build) {
        build.onEnd(async (result) => {
          if (result.errors.length > 0) return;

          await stripTrailingWhitespace(outFile);
          await rm(cssOutFile, { force: true });
          await syncHostCopies();
          console.log(
            `Synced editor bundle to ${hostCopies
              .map((target) => target.replace("../", ""))
              .join(", ")}`
          );
        });
      },
    },
  ],
});

if (watch) {
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await ctx.rebuild();
  await ctx.dispose();
  console.log("Build complete: assets/editor.js");
}
